#!/usr/bin/env python
import plot_PSEC as plt

import tkFileDialog
import tkMessageBox


cwd = os.getcwd()
# Get the data file from a dialogue box adn open it. Also store the filename.
f = tkFileDialog.askopenfile(mode='rb', initialfile=cwd, title='Select a file', filetypes = (("Text Files","*.txt"),("all files","*.*")))
fname = f.name
oname = fname
f.close()

oname = oname.strip('.txt').replace('DATA', 'FIGS')+'.html'

plt.plot_PSEC(fname, oname)

