#!/usr/bin/env python
import bokeh.plotting as bkh
from bokeh.models import Range1d
from bokeh.models import HoverTool
import os
import datetime
import subprocess
import tkFileDialog
import tkMessageBox
import plot_PSEC4 as plt

### FILEPATH TO PSEC4 CODE DIRECTORY!!! SET THIS!!!!!! ###
DIR = '/home/wizenedchimp/Documents/LAPPD-Project/run-psec4-master/'
DIR = '/home/wizenedchimp/Downloads'

def find(name, path):
    result = ''
    for root, dirs, files in os.walk(path):
        if name in files:
            result = os.path.join(root, name)
            break
    return result

try:
	DIR
except:
	print 'PSEC directory not set! Attempting to search for it...'
	DIR = find('TakePed', '/home')[:-12]
	print DIR

if not os.path.exists(DIR):
	print 'PSEC directory not set! Attempting to search for it...'
	DIR = find('TakePed', '/home')[:-12]
	print DIR

os.chdir(DIR)
# print 'working in directory:\n %s' % DIR

oname = raw_input('Please enter a filename (blank for automatic):')
if oname == '':
	t = datetime.datetime.now()
	oname = 'sample_'+str(t.year)+'-'+str(t.month)+'-'+str(t.day)+'_'+str(t.hour)+'h'+str(t.minute)+'m'

# Check if the DATA and FIGS paths exist, and if not create them.
if not os.path.exists('./DATA/'):
	print 'DATA directory not found. Creating a folder...'
	os.makedirs('./DATA/')
if not os.path.exists('./FIGS/'):
	print 'FIGS directory not found. Creating a folder...'
	os.makedirs('./FIGS/')

oname = './DATA/'+oname
print 'Writing to %s.txt' % (oname)
N = ''
i = 0
while type(N) != int:
	N = raw_input('Please enter the number of samples you want to take: ')
	try:
		N = int(N)
	except:
		i += 1
		if i > 2:
			print '...Why are you like this'
		print '\n'

# Ask the PSEC to read the thing, and store it in DATA with the name we want
command = ['./bin/LogData', oname, str(N), '0']
psec = subprocess.Popen(command)
psec.wait()

# If we can't find the file after the PSEC is done, exit
if not os.path.isfile(oname+'.txt'):
	print 'Unable to find %s.txt! Stopping...' % oname
	exit()

p = plt.plot_PSEC(oname+'.txt', oname=oname.replace('DATA', 'FIGS'))


bkh.save(p)
bkh.show(p)